name: Publish plugin

on: push

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          skip_test: true
